"""
Master Ingestion Pipeline Orchestration CLI for SSC CGL Question Bank
Supports paper_import_status tracking and per-paper quality reporting.
"""
import os
import sys
import json
import time
import argparse
from typing import Dict, List, Any

sys.path.insert(0, os.path.dirname(__file__))

from pdf_classifier import scan_pdf_directory
from pdf_extractor import extract_questions_from_pdf
from validator import process_and_validate_questions

def generate_sql_seed_file(validated_questions: List[Dict[str, Any]], raw_questions: List[Dict[str, Any]], paper_import_records: List[Dict[str, Any]], out_sql_path: str):
    """Generates PostgreSQL SQL seed file for Supabase database insertion."""
    def clean_str(val):
        if val is None:
            return "NULL"
        escaped = str(val).replace("'", "''").replace("\\", "\\\\")
        return f"'{escaped}'"

    lines = [
        "-- Supabase Seed SQL for SSC CGL Extracted Question Bank",
        "-- Auto-generated by Production Ingestion Pipeline\n",
        "BEGIN;\n"
    ]

    # 1. Insert Paper Import Status
    lines.append("-- 1. Insert Paper Import Status")
    for r in paper_import_records:
        stmt = f"""INSERT INTO public.paper_import_status (
            paper_name, year, shift, expected_questions, raw_records, validated_questions,
            manual_review, duplicates, missing_answers, missing_options, status, validation_percentage, last_imported_at
        ) VALUES (
            {clean_str(r['paper_name'])}, {r['year']}, {clean_str(r['shift'])}, {r['expected_questions']}, {r['raw_records']},
            {r['validated_questions']}, {r['manual_review']}, {r['duplicates']}, {r['missing_answers']}, {r['missing_options']},
            {clean_str(r['status'])}, {r['validation_percentage']}, now()
        ) ON CONFLICT (paper_name) DO UPDATE SET
            validated_questions = EXCLUDED.validated_questions,
            raw_records = EXCLUDED.raw_records,
            manual_review = EXCLUDED.manual_review,
            duplicates = EXCLUDED.duplicates,
            missing_answers = EXCLUDED.missing_answers,
            missing_options = EXCLUDED.missing_options,
            status = EXCLUDED.status,
            validation_percentage = EXCLUDED.validation_percentage,
            last_imported_at = now();"""
        lines.append(stmt)

    # 2. Insert Raw Questions
    lines.append("\n-- 2. Insert Raw Questions (Staging)")
    for q in raw_questions:
        qnum = q.get('question_number') if q.get('question_number') is not None else "NULL"
        year = q.get('year') if q.get('year') is not None else "NULL"
        v_errs = json.dumps(q.get('validation_errors')).replace("'", "''") if q.get('validation_errors') else "NULL"
        if v_errs != "NULL":
            v_errs = f"'{v_errs}'::jsonb"

        stmt = f"""INSERT INTO public.raw_questions (
            id, paper_name, year, shift, subject, question_number, question_text, question_image,
            option_a, option_b, option_c, option_d, correct_answer, official_explanation, marks, negative_marks, source_pdf, extraction_status, validation_errors
        ) VALUES (
            '{q['id']}', {clean_str(q.get('paper_name'))}, {year}, {clean_str(q.get('shift'))}, {clean_str(q.get('subject'))}, {qnum},
            {clean_str(q.get('question_text'))}, {clean_str(q.get('question_image'))}, {clean_str(q.get('option_a'))}, {clean_str(q.get('option_b'))},
            {clean_str(q.get('option_c'))}, {clean_str(q.get('option_d'))}, {clean_str(q.get('correct_answer'))}, {clean_str(q.get('official_explanation'))},
            {q.get('marks', 2.0)}, {q.get('negative_marks', 0.5)}, {clean_str(q['source_pdf'])}, {clean_str(q['extraction_status'])}, {v_errs}
        ) ON CONFLICT (id) DO NOTHING;"""
        lines.append(stmt)

    # 3. Insert Validated Questions
    lines.append("\n-- 3. Insert Validated Questions (Production)")
    for q in validated_questions:
        qnum = q.get('question_number') if q.get('question_number') is not None else "NULL"
        year = q.get('year') if q.get('year') is not None else "NULL"
        stmt = f"""INSERT INTO public.validated_questions (
            id, paper_name, year, shift, subject, question_number, question_text, question_image,
            option_a, option_b, option_c, option_d, correct_answer, official_explanation, marks, negative_marks, source_pdf, is_validated
        ) VALUES (
            '{q['id']}', {clean_str(q.get('paper_name'))}, {year}, {clean_str(q.get('shift'))}, {clean_str(q.get('subject'))}, {qnum},
            {clean_str(q.get('question_text'))}, {clean_str(q.get('question_image'))}, {clean_str(q.get('option_a'))}, {clean_str(q.get('option_b'))},
            {clean_str(q.get('option_c'))}, {clean_str(q.get('option_d'))}, {clean_str(q.get('correct_answer'))}, {clean_str(q.get('official_explanation'))},
            {q.get('marks', 2.0)}, {q.get('negative_marks', 0.5)}, {clean_str(q['source_pdf'])}, true
        ) ON CONFLICT (paper_name, question_number) DO NOTHING;"""
        lines.append(stmt)

    lines.append("\nCOMMIT;")

    os.makedirs(os.path.dirname(out_sql_path), exist_ok=True)
    with open(out_sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated SQL seed file: {out_sql_path}")

def generate_paper_quality_report(paper_import_records: List[Dict[str, Any]]):
    """Generates comprehensive paper quality report in Markdown format."""
    os.makedirs("reports", exist_ok=True)
    report_path = os.path.join("reports", "paper_quality_report.md")

    total_expected = sum(r["expected_questions"] for r in paper_import_records)
    total_validated = sum(r["validated_questions"] for r in paper_import_records)
    total_raw = sum(r["raw_records"] for r in paper_import_records)
    overall_pct = (total_validated / total_expected * 100) if total_expected else 0

    md = f"""# SSC CGL Paper Quality & Validation Report

**Generated:** {time.strftime('%Y-%m-%d %H:%M:%S')}

## Overall Performance

| Metric | Overall Total |
| :--- | :--- |
| **Total Papers Processed** | `{len(paper_import_records)}` |
| **Total Expected Questions** | `{total_expected}` |
| **Total Raw Records Extracted** | `{total_raw}` |
| **Total Validated Questions Promoted** | `{total_validated}` |
| **Overall Validation Success Rate** | **`{overall_pct:.2f}%`** |

## Per-Paper Import Quality Audit

| Paper Name | Year | Shift | Expected | Extracted | Validated | Manual Review | Duplicates | Missing Ans | Missing Opts | Validation % | Status |
| :--- | :--- | :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :--- |
"""
    for r in paper_import_records:
        status_icon = "✅ SUCCESS" if r["status"] == "SUCCESS" else ("⚠️ REVIEW" if r["status"] == "NEEDS_REVIEW" else "❌ FAILED")
        md += f"| `{r['paper_name']}` | `{r['year']}` | `{r['shift']}` | `{r['expected_questions']}` | `{r['raw_records']}` | `{r['validated_questions']}` | `{r['manual_review']}` | `{r['duplicates']}` | `{r['missing_answers']}` | `{r['missing_options']}` | `{r['validation_percentage']:.1f}%` | {status_icon} |\n"

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"Saved paper quality report to: {report_path}")

def run_ingestion(pdf_dir: str, img_out_dir: str = "public/question-images"):
    """Main execution workflow for scanning, extracting, validating, and seeding PDF questions."""
    sys.stdout.reconfigure(encoding='utf-8')
    os.makedirs("reports", exist_ok=True)
    os.makedirs("scratch", exist_ok=True)

    print("==================================================")
    print("STARTING PRODUCTION SSC CGL EXTRACTION PIPELINE")
    print("==================================================")

    # Step 1: Scan and classify PDFs
    print("\n[STEP 1] Scanning and classifying PDFs...")
    inventory = scan_pdf_directory(pdf_dir)
    print(f"Scanned {len(inventory)} PDF files.")

    # Step 2: Extract Questions from PDFs
    print("\n[STEP 2] Extracting questions via spatial bounding-box parser...")
    all_raw_questions = []
    pdf_logs = []

    for item in inventory:
        fname = item["filename"]
        fpath = item["filepath"]
        print(f"Extracting: {fname}...")
        try:
            raw_qs = extract_questions_from_pdf(fpath, item, img_out_dir)
            all_raw_questions.extend(raw_qs)
            
            pdf_logs.append({
                "pdf_filename": fname,
                "pdf_type": item["pdf_type"],
                "year": item["year"],
                "shift": item["shift"],
                "raw_count": len(raw_qs),
                "val_count": 0,
                "flagged_count": 0
            })
        except Exception as e:
            print(f"Error extracting {fname}: {e}")

    print(f"Extracted {len(all_raw_questions)} total raw question records.")

    # Step 3: Run Zero-Hallucination Validation Engine
    print("\n[STEP 3] Running Zero-Hallucination Validation Engine...")
    validated, failed, review_queue, paper_metrics = process_and_validate_questions(all_raw_questions)

    # Calculate per-paper import records
    paper_import_records = []
    for pname, metrics in paper_metrics.items():
        # Infer expected questions: 150 for Tier II / Mains, 100 for Tier I
        expected = 150 if ("Tier II" in pname or "Tier-II" in pname or "Paper-I" in pname or "Mains" in pname) else 100
        val_c = metrics["validated_questions"]
        val_pct = (val_c / expected * 100.0) if expected else 0.0
        
        status = "SUCCESS" if val_pct >= 95.0 else ("NEEDS_REVIEW" if val_pct >= 50.0 else "FAILED")
        
        # Get year/shift
        yr = 2024
        sh = "Shift 1"
        for item in inventory:
            if item["paper_name"] == pname or item["filename"].replace(".pdf", "") == pname:
                yr = item["year"]
                sh = item["shift"]
                break

        paper_import_records.append({
            "paper_name": pname,
            "year": yr,
            "shift": sh,
            "expected_questions": expected,
            "raw_records": metrics["raw_records"],
            "validated_questions": val_c,
            "manual_review": metrics["manual_review"],
            "duplicates": metrics["duplicates"],
            "missing_answers": metrics["missing_answers"],
            "missing_options": metrics["missing_options"],
            "status": status,
            "validation_percentage": round(val_pct, 2)
        })

    print(f"-> Promoted to validated_questions: {len(validated)}")
    print(f"-> Flagged for manual review: {len(failed)}")

    # Step 4: Save JSON Reports & SQL Seeds
    print("\n[STEP 4] Generating SQL Seeds & Reports...")
    
    with open(os.path.join("reports", "extraction_logs.json"), "w", encoding="utf-8") as f:
        json.dump(pdf_logs, f, indent=2)

    with open(os.path.join("reports", "manual_review_list.json"), "w", encoding="utf-8") as f:
        json.dump(review_queue, f, indent=2)

    with open(os.path.join("scratch", "validated_questions_export.json"), "w", encoding="utf-8") as f:
        json.dump(validated, f, indent=2)

    sql_seed_path = os.path.join("supabase", "seed_validated_questions.sql")
    generate_sql_seed_file(validated, all_raw_questions, paper_import_records, sql_seed_path)

    generate_paper_quality_report(paper_import_records)

    print("\n==================================================")
    print("PRODUCTION EXTRACTION PIPELINE COMPLETED!")
    print(f"Total Validated Questions Ready: {len(validated)}")
    print("==================================================")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SSC CGL Production PDF Ingestion Pipeline")
    parser.add_argument("--pdf-dir", default=r"c:\Users\jijo1\OneDrive\Desktop\Lastmileprep latest\ssc cgl\English", help="Path to PDF directory")
    args = parser.parse_args()

    run_ingestion(args.pdf_dir)
