-- ============================================================================
-- Migration 20260929000000: IBPS Clerk Prelims namespace (multi-exam step 6a)
--
-- IBPS Clerk is its OWN entity, hard-isolated in the `ibps_clerk` schema (no
-- shared content table with SSC or SBI). The Prelims blueprint matches SBI Clerk
-- Prelims in shape: 5 options (A–E), 1/−0.25 marking, 3 sections
-- (English 30 / Numerical 35 / Reasoning 35), 20-min sectional locks, 60-min
-- total. The shared answer columns are already A–E (widened in
-- 20260925000300 for SBI), so nothing on the shared tables changes here.
--
-- Reversible: drop schema ibps_clerk cascade + the public ibps_clerk__* views +
-- the exams row.
-- ============================================================================
BEGIN;

CREATE SCHEMA IF NOT EXISTS ibps_clerk;

-- 1. IBPS content tables mirror the SSC structure (LIKE), then the answer key is
--    widened to A–E and intra-schema FKs are (re)added (LIKE doesn't copy FKs).
CREATE TABLE ibps_clerk.papers             (LIKE ssc_cgl.papers INCLUDING ALL);
CREATE TABLE ibps_clerk.questions          (LIKE ssc_cgl.questions INCLUDING ALL);
CREATE TABLE ibps_clerk.question_assets    (LIKE ssc_cgl.question_assets INCLUDING ALL);
CREATE TABLE ibps_clerk.excluded_questions (LIKE ssc_cgl.excluded_questions INCLUDING ALL);

-- widen the copied correct_option CHECK (its name is auto-generated by LIKE).
DO $$
DECLARE cn text;
BEGIN
  SELECT conname INTO cn FROM pg_constraint
   WHERE conrelid = 'ibps_clerk.questions'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%correct_option%';
  IF cn IS NOT NULL THEN EXECUTE format('ALTER TABLE ibps_clerk.questions DROP CONSTRAINT %I', cn); END IF;
END $$;
ALTER TABLE ibps_clerk.questions ADD CONSTRAINT ibps_questions_correct_option_check
  CHECK (correct_option = ANY (ARRAY['A','B','C','D','E']::bpchar[]));

-- Memory-based papers may have an unknown year (hash-named sources). Storing NULL
-- is correct here — never fabricate a year — so relax the copied NOT NULL.
ALTER TABLE ibps_clerk.papers ALTER COLUMN year DROP NOT NULL;

-- The paper_type + section CHECKs were copied from SSC (LIKE). IBPS papers are
-- memory-based, and its sections are english/numerical_ability/reasoning (not the
-- SSC slugs). Replace both for this content table only.
DO $$
DECLARE cn text;
BEGIN
  SELECT conname INTO cn FROM pg_constraint
   WHERE conrelid = 'ibps_clerk.papers'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%paper_type%';
  IF cn IS NOT NULL THEN EXECUTE format('ALTER TABLE ibps_clerk.papers DROP CONSTRAINT %I', cn); END IF;
END $$;
ALTER TABLE ibps_clerk.papers ADD CONSTRAINT ibps_papers_paper_type_check
  CHECK (paper_type = ANY (ARRAY[
    'official_question_paper','tcs_response_sheet','official_answer_key','solved_book',
    'similar_practice_paper','candidate_summary','incomplete_scan','unsupported_document','memory_based'
  ]));

DO $$
DECLARE cn text;
BEGIN
  SELECT conname INTO cn FROM pg_constraint
   WHERE conrelid = 'ibps_clerk.questions'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%section%';
  IF cn IS NOT NULL THEN EXECUTE format('ALTER TABLE ibps_clerk.questions DROP CONSTRAINT %I', cn); END IF;
END $$;
ALTER TABLE ibps_clerk.questions ADD CONSTRAINT ibps_questions_section_check
  CHECK (section = ANY (ARRAY['english','numerical_ability','reasoning']));

ALTER TABLE ibps_clerk.questions          ADD CONSTRAINT questions_paper_id_fkey        FOREIGN KEY (paper_id)    REFERENCES ibps_clerk.papers(paper_id);
ALTER TABLE ibps_clerk.question_assets    ADD CONSTRAINT question_assets_paper_id_fkey  FOREIGN KEY (paper_id)    REFERENCES ibps_clerk.papers(paper_id);
ALTER TABLE ibps_clerk.question_assets    ADD CONSTRAINT question_assets_question_id_fkey FOREIGN KEY (question_id) REFERENCES ibps_clerk.questions(id) ON DELETE CASCADE;
ALTER TABLE ibps_clerk.excluded_questions ADD CONSTRAINT excluded_questions_question_id_fkey FOREIGN KEY (question_id) REFERENCES ibps_clerk.questions(id) ON DELETE CASCADE;

-- 2. Per-exam public views (the content-repo reads ibps_clerk__* — never the base
--    schema directly). validated maps section→subject + flattens 5 options.
CREATE VIEW public.ibps_clerk__validated_questions AS
SELECT
  q.id, q.paper_id,
  p.paper_name_canonical AS paper_name, p.year, p.shift,
  CASE q.section
    WHEN 'english'           THEN 'English Language'
    WHEN 'numerical_ability' THEN 'Numerical Ability'
    WHEN 'reasoning'         THEN 'Reasoning Ability'
    ELSE q.section
  END AS subject,
  q.question_number, q.stem_text AS question_text, NULL::text AS question_image,
  COALESCE(NULLIF((q.options -> 0) ->> 'text', ''), CASE WHEN ((q.options -> 0) ->> 'isImage')::boolean THEN '[image]' END) AS option_a,
  COALESCE(NULLIF((q.options -> 1) ->> 'text', ''), CASE WHEN ((q.options -> 1) ->> 'isImage')::boolean THEN '[image]' END) AS option_b,
  COALESCE(NULLIF((q.options -> 2) ->> 'text', ''), CASE WHEN ((q.options -> 2) ->> 'isImage')::boolean THEN '[image]' END) AS option_c,
  COALESCE(NULLIF((q.options -> 3) ->> 'text', ''), CASE WHEN ((q.options -> 3) ->> 'isImage')::boolean THEN '[image]' END) AS option_d,
  COALESCE(NULLIF((q.options -> 4) ->> 'text', ''), CASE WHEN ((q.options -> 4) ->> 'isImage')::boolean THEN '[image]' END) AS option_e,
  q.correct_option AS correct_answer, q.solution_text AS official_explanation,
  q.marks, q.negative_marks, q.source_document AS source_pdf, q.dataset_version,
  q.section AS section_slug, COALESCE(q.has_images, false) AS has_images
FROM ibps_clerk.questions q
JOIN ibps_clerk.papers p ON p.paper_id = q.paper_id;

CREATE VIEW public.ibps_clerk__cbt_valid_questions AS
SELECT v.*
FROM public.ibps_clerk__validated_questions v
JOIN ibps_clerk.papers p ON p.paper_id = v.paper_id
WHERE p.published
  AND v.correct_answer = ANY (ARRAY['A','B','C','D','E'::bpchar])
  AND COALESCE(btrim(v.option_a), '') <> ''
  AND COALESCE(btrim(v.option_b), '') <> ''
  AND COALESCE(btrim(v.option_c), '') <> ''
  AND COALESCE(btrim(v.option_d), '') <> ''
  AND COALESCE(btrim(v.option_e), '') <> ''
  AND (COALESCE(btrim(v.question_text), '') <> '' OR v.has_images IS TRUE
       OR '[image]' IN (v.option_a, v.option_b, v.option_c, v.option_d, v.option_e))
  AND COALESCE(v.question_text, '') !~ '[ऀ-ॿ]'
  AND NOT EXISTS (SELECT 1 FROM ibps_clerk.excluded_questions e WHERE e.question_id = v.id);

-- 3. Raw pass-through views (content-repo reads ibps_clerk__questions etc.).
CREATE OR REPLACE VIEW public.ibps_clerk__questions           AS SELECT * FROM ibps_clerk.questions;
CREATE OR REPLACE VIEW public.ibps_clerk__papers             AS SELECT * FROM ibps_clerk.papers;
CREATE OR REPLACE VIEW public.ibps_clerk__question_assets    AS SELECT * FROM ibps_clerk.question_assets;
CREATE OR REPLACE VIEW public.ibps_clerk__excluded_questions AS SELECT * FROM ibps_clerk.excluded_questions;

-- 4. IBPS Clerk Prelims exam config (SSOT; matches IBPS_CLERK_PRELIMS_CONFIG).
INSERT INTO public.exams (slug, name, config)
VALUES (
  'ibps-clerk-prelims', 'IBPS Clerk Prelims',
  '{
    "schemaVersion":1,"examSlug":"ibps-clerk-prelims","examName":"IBPS Clerk Prelims","tier":null,
    "totalDurationMinutes":60,"hasSectionTimeLocks":true,"defaultLanguage":"en","negativeMarking":true,
    "marksCorrect":1,"marksWrong":-0.25,"optionsCount":5,
    "sections":[
      {"key":"english","name":"English Language","order":1,"questionCount":30,"marksCorrect":1,"marksWrong":-0.25,"questionType":"single_correct_mcq","optionsCount":5,"timeLimitMinutes":20},
      {"key":"numerical_ability","name":"Numerical Ability","order":2,"questionCount":35,"marksCorrect":1,"marksWrong":-0.25,"questionType":"single_correct_mcq","optionsCount":5,"timeLimitMinutes":20},
      {"key":"reasoning","name":"Reasoning Ability","order":3,"questionCount":35,"marksCorrect":1,"marksWrong":-0.25,"questionType":"single_correct_mcq","optionsCount":5,"timeLimitMinutes":20}
    ]
  }'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, config = EXCLUDED.config, updated_at = now();

COMMIT;
