-- ============================================================================
-- Migration 20260925000300: SBI Clerk Prelims namespace (multi-exam step 5a)
--
-- SBI is its OWN entity: 5 options (A–E), 1/−0.25 marking, 3 sections, 20-min
-- sectional locks. Content is hard-isolated in the `sbi_clerk` schema (no shared
-- table with SSC). Shared answer columns are widened to A–E (backward-compatible
-- with SSC's A–D). Nothing SSC changes.
--
-- Reversible: supabase/manual/rollback_20260925000300.sql
-- ============================================================================
BEGIN;

CREATE SCHEMA IF NOT EXISTS sbi_clerk;

-- 1. Shared answer columns allow A–E now (banking 5-option). SSC never uses E,
--    so this is a pure widening — no SSC impact.
ALTER TABLE public.attempt_answers DROP CONSTRAINT IF EXISTS attempt_answers_selected_option_check;
ALTER TABLE public.attempt_answers ADD  CONSTRAINT attempt_answers_selected_option_check
  CHECK (selected_option = ANY (ARRAY['A','B','C','D','E']));
ALTER TABLE public.responses DROP CONSTRAINT IF EXISTS responses_selected_option_check;
ALTER TABLE public.responses ADD  CONSTRAINT responses_selected_option_check
  CHECK (selected_option = ANY (ARRAY['A','B','C','D','E']::bpchar[]));

-- 2. SBI content tables mirror the SSC structure (LIKE), then the answer key is
--    widened to A–E and intra-schema FKs are (re)added (LIKE doesn't copy FKs).
CREATE TABLE sbi_clerk.papers             (LIKE ssc_cgl.papers INCLUDING ALL);
CREATE TABLE sbi_clerk.questions          (LIKE ssc_cgl.questions INCLUDING ALL);
CREATE TABLE sbi_clerk.question_assets    (LIKE ssc_cgl.question_assets INCLUDING ALL);
CREATE TABLE sbi_clerk.excluded_questions (LIKE ssc_cgl.excluded_questions INCLUDING ALL);

-- widen the copied correct_option CHECK (its name is auto-generated by LIKE).
DO $$
DECLARE cn text;
BEGIN
  SELECT conname INTO cn FROM pg_constraint
   WHERE conrelid = 'sbi_clerk.questions'::regclass AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%correct_option%';
  IF cn IS NOT NULL THEN EXECUTE format('ALTER TABLE sbi_clerk.questions DROP CONSTRAINT %I', cn); END IF;
END $$;
ALTER TABLE sbi_clerk.questions ADD CONSTRAINT sbi_questions_correct_option_check
  CHECK (correct_option = ANY (ARRAY['A','B','C','D','E']::bpchar[]));

ALTER TABLE sbi_clerk.questions          ADD CONSTRAINT questions_paper_id_fkey        FOREIGN KEY (paper_id)    REFERENCES sbi_clerk.papers(paper_id);
ALTER TABLE sbi_clerk.question_assets    ADD CONSTRAINT question_assets_paper_id_fkey  FOREIGN KEY (paper_id)    REFERENCES sbi_clerk.papers(paper_id);
ALTER TABLE sbi_clerk.question_assets    ADD CONSTRAINT question_assets_question_id_fkey FOREIGN KEY (question_id) REFERENCES sbi_clerk.questions(id) ON DELETE CASCADE;
ALTER TABLE sbi_clerk.excluded_questions ADD CONSTRAINT excluded_questions_question_id_fkey FOREIGN KEY (question_id) REFERENCES sbi_clerk.questions(id) ON DELETE CASCADE;

-- 3. Per-exam public views (the content-repo reads sbi_clerk__* — never the base
--    schema directly). validated maps section→subject + flattens 5 options.
CREATE VIEW public.sbi_clerk__validated_questions AS
SELECT
  q.id, q.paper_id,
  p.paper_name_canonical AS paper_name, p.year, p.shift,
  CASE q.section
    WHEN 'english'           THEN 'English Language'
    WHEN 'numerical_ability' THEN 'Numerical Ability'
    WHEN 'reasoning'         THEN 'Reasoning Ability'
    ELSE q.section
  END AS subject,
  q.question_number, q.stem_text AS question_text, NULL::text AS question_image,
  COALESCE(NULLIF((q.options -> 0) ->> 'text', ''), CASE WHEN ((q.options -> 0) ->> 'isImage')::boolean THEN '[image]' END) AS option_a,
  COALESCE(NULLIF((q.options -> 1) ->> 'text', ''), CASE WHEN ((q.options -> 1) ->> 'isImage')::boolean THEN '[image]' END) AS option_b,
  COALESCE(NULLIF((q.options -> 2) ->> 'text', ''), CASE WHEN ((q.options -> 2) ->> 'isImage')::boolean THEN '[image]' END) AS option_c,
  COALESCE(NULLIF((q.options -> 3) ->> 'text', ''), CASE WHEN ((q.options -> 3) ->> 'isImage')::boolean THEN '[image]' END) AS option_d,
  COALESCE(NULLIF((q.options -> 4) ->> 'text', ''), CASE WHEN ((q.options -> 4) ->> 'isImage')::boolean THEN '[image]' END) AS option_e,
  q.correct_option AS correct_answer, q.solution_text AS official_explanation,
  q.marks, q.negative_marks, q.source_document AS source_pdf, q.dataset_version,
  q.section AS section_slug, COALESCE(q.has_images, false) AS has_images
FROM sbi_clerk.questions q
JOIN sbi_clerk.papers p ON p.paper_id = q.paper_id;

CREATE VIEW public.sbi_clerk__cbt_valid_questions AS
SELECT v.*
FROM public.sbi_clerk__validated_questions v
JOIN sbi_clerk.papers p ON p.paper_id = v.paper_id
WHERE p.published
  AND v.correct_answer = ANY (ARRAY['A','B','C','D','E'::bpchar])
  AND COALESCE(btrim(v.option_a), '') <> ''
  AND COALESCE(btrim(v.option_b), '') <> ''
  AND COALESCE(btrim(v.option_c), '') <> ''
  AND COALESCE(btrim(v.option_d), '') <> ''
  AND COALESCE(btrim(v.option_e), '') <> ''
  AND (COALESCE(btrim(v.question_text), '') <> '' OR v.has_images IS TRUE
       OR '[image]' IN (v.option_a, v.option_b, v.option_c, v.option_d, v.option_e))
  AND COALESCE(v.question_text, '') !~ '[ऀ-ॿ]'
  AND NOT EXISTS (SELECT 1 FROM sbi_clerk.excluded_questions e WHERE e.question_id = v.id);

-- 4. SBI Clerk Prelims exam config (SSOT; matches SBI_CLERK_PRELIMS_CONFIG).
INSERT INTO public.exams (slug, name, config)
VALUES (
  'sbi-clerk-prelims', 'SBI Clerk Prelims',
  '{
    "schemaVersion":1,"examSlug":"sbi-clerk-prelims","examName":"SBI Clerk Prelims","tier":null,
    "totalDurationMinutes":60,"hasSectionTimeLocks":true,"defaultLanguage":"en","negativeMarking":true,
    "marksCorrect":1,"marksWrong":-0.25,"optionsCount":5,
    "sections":[
      {"key":"english","name":"English Language","order":1,"questionCount":30,"marksCorrect":1,"marksWrong":-0.25,"questionType":"single_correct_mcq","optionsCount":5,"timeLimitMinutes":20},
      {"key":"numerical_ability","name":"Numerical Ability","order":2,"questionCount":35,"marksCorrect":1,"marksWrong":-0.25,"questionType":"single_correct_mcq","optionsCount":5,"timeLimitMinutes":20},
      {"key":"reasoning","name":"Reasoning Ability","order":3,"questionCount":35,"marksCorrect":1,"marksWrong":-0.25,"questionType":"single_correct_mcq","optionsCount":5,"timeLimitMinutes":20}
    ]
  }'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, config = EXCLUDED.config, updated_at = now();

COMMIT;
